name: "blint"
description: "Scan binaries for capabilities."
inputs:
  reports_dir:
    description: "Report output directory. Defaults to /workspace/reports."
    required: false
    default: "/github/workspace/reports"
  src:
    description: "Directories or images. Defaults to workspace."
    required: false
    default: "/github/workspace"

runs:
  using: "docker"
  image: "docker://ghcr.io/appthreat/blint:v1.0.33-beta.1"
  args:
    - "-o"
    - ${{ inputs.reports_dir }}
    - "-i"
    - ${{ inputs.src }}
