name: "blint"
description: "Scan binaries for capabilities."
inputs:
  src:
    description: "Directories or images. Defaults to workspace."
    required: false
    default: "/github/workspace"

runs:
  using: "docker"
  image: "docker://ghcr.io/appthreat/blint:feature-blint-action"
  env:
    IS_GHA: 1
  args:
    - -o
    - "/github/workspace/reports"
    - -i
    - ${{ inputs.src }}
